name: matrix and conditions

on:
  workflow_dispatch:
    
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  matrix-job:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        number: [1,2]
        letter: [a,b,c]
        exclude:
          - number: 1
            letter: c